"""Contenido del sitio de GC Legal.

Todo el texto de los servicios vive aquí para que el equipo pueda editarlo
sin tocar las plantillas. Después de editar, ejecuta:  python3 scripts/build.py
"""

# Versión beta: evita que los buscadores indexen el sitio mientras tenga datos
# de prueba. Cambiar a False al lanzar la versión real.
BETA = True

# --------------------------------------------------------------------------
# Datos de contacto (placeholders — reemplazar por los reales)
# --------------------------------------------------------------------------
FIRM = {
    "name": "GC Legal",
    "legal_name": "Gómez & Cadena Abogados",
    "slogan": "Derecho a la solución",
    "whatsapp": "573113973304",
    "whatsapp_display": "+57 311 397 3304",
    "email": "contacto@gclegal.co",       # ← confirmar
    "instagram": "https://www.instagram.com/gclegal.co",
    "instagram_handle": "@gclegal.co",
    "linkedin": "https://www.linkedin.com/company/gclegal",
    "city": "Rionegro",
    "region": "Antioquia",
    "country": "Colombia",
    "hours": "Lunes a viernes, 8:00 a.m. – 6:00 p.m.",
    "site_url": "https://gomezcadena.com",  # ← dominio (canonical, Open Graph, schema, sitemap)
}

CATEGORIES = {
    "empresas": {
        "name": "Empresas",
        "title": "Servicios jurídicos para empresas",
        "short": "Para empresas",
        "lead": "Desde el día en que constituyes tu sociedad hasta la operación diaria: contratos, marcas, datos personales y documentos corporativos con tarifa fija y un abogado que entiende tu negocio.",
        "meta_title": "Servicios jurídicos para empresas en Colombia | GC Legal",
        "meta_desc": "Constitución de SAS, contratos comerciales, registro de marcas, protección de datos, gobierno corporativo y asesoría mensual. Tarifas fijas, atención digital y en Rionegro.",
        "intro": [
            "Emprender y crecer en Colombia implica cumplir con Cámara de Comercio, DIAN, Superintendencias y un sinfín de reglas que cambian. Lo sabemos porque acompañamos empresas todos los días.",
            "Por eso empaquetamos los servicios jurídicos que más necesita una empresa con alcance definido, plazo estimado y tarifa fija. Tú te enfocas en tu negocio; nosotros en que esté bien protegido.",
        ],
    },
    "personas": {
        "name": "Personas",
        "title": "Servicios jurídicos para personas",
        "short": "Para personas",
        "lead": "Situaciones familiares y derechos fundamentales que necesitan una respuesta seria, rápida y humana. Te explicamos tus opciones en palabras claras y te acompañamos hasta el final.",
        "meta_title": "Abogados de familia y tutelas en Rionegro, Antioquia | GC Legal",
        "meta_desc": "Divorcios, liquidación de sociedad conyugal, custodia, alimentos y acciones de tutela. Asesoría clara, reservada y con cotización previa. Atención digital y presencial.",
        "intro": [
            "Cuando un asunto legal toca tu familia o tus derechos, lo último que necesitas es incertidumbre. Te decimos desde el principio qué camino tienes, cuánto puede tardar y cuánto cuesta.",
            "Tratamos cada caso con reserva y respeto. Puedes consultarnos por WhatsApp desde cualquier lugar de Colombia o reunirte con nosotros en Rionegro.",
        ],
    },
}

# --------------------------------------------------------------------------
# Servicios
# --------------------------------------------------------------------------
SERVICES = [
    # ------------------------------------------------------------------ SAS
    {
        "slug": "constitucion-sas",
        "cat": "empresas",
        "icon": "building",
        "name": "Constitución de SAS",
        "nav_desc": "Tu sociedad lista para operar",
        "short": "Crea tu sociedad en Colombia con todos los documentos legales. Tarifa fija.",
        "long": "Formaliza tu negocio con una Sociedad por Acciones Simplificada: estatutos a la medida, inscripción en Cámara de Comercio y NIT, sin vueltas ni filas.",
        "card_points": ["Estatutos personalizados", "Registro en Cámara de Comercio", "NIT y RUT de la sociedad"],
        "h1": "Constitución de SAS",
        "h1_sub": "Tu empresa legalmente constituida",
        "intro": "Constituimos tu Sociedad por Acciones Simplificada con estatutos pensados para tu negocio y no copiados de una plantilla. Nos encargamos del registro ante la Cámara de Comercio y del NIT para que empieces a facturar con tranquilidad.",
        "delivery": "5–10 días hábiles",
        "ideal": "Emprendedores, profesionales independientes que quieren formalizarse y negocios que crecen con nuevos socios.",
        "wa": "la constitución de una SAS",
        "meta_title": "Constitución de SAS en Colombia con tarifa fija | GC Legal",
        "meta_desc": "Constituimos tu SAS con estatutos personalizados, registro en Cámara de Comercio y NIT/RUT. Tarifa fija, proceso 100 % digital y entrega en 5 a 10 días hábiles.",
        "what_title": "¿Por qué constituir tu empresa como SAS?",
        "what": [
            "Operar como persona natural mezcla tu patrimonio con el del negocio: si algo sale mal, respondes con tus bienes personales. La <strong>Sociedad por Acciones Simplificada</strong> (Ley 1258 de 2008) separa ambos patrimonios y limita tu responsabilidad al monto de tus aportes.",
            "Es la figura más usada en Colombia porque es flexible: puede tener un solo accionista, no exige capital mínimo y se constituye por documento privado, sin escritura pública en la mayoría de los casos. Además facilita la entrada de inversionistas y socios.",
            "El problema es que muchos emprendedores usan estatutos genéricos que no dicen nada sobre cómo entran o salen los socios, quién decide qué o qué pasa si hay un conflicto. Nosotros redactamos estatutos que responden esas preguntas desde el día uno.",
        ],
        "includes": [
            ("Asesoría sobre estructura societaria", "Accionistas, capital, órganos y facultades del representante legal."),
            ("Estatutos sociales personalizados", "Reglas claras sobre socios, decisiones y salida de accionistas."),
            ("Documento de constitución", "Listo para firma, también de forma electrónica."),
            ("Registro ante la Cámara de Comercio", "Radicación y seguimiento hasta la inscripción."),
            ("Trámite del pre-RUT, NIT y RUT", "Coordinamos la asignación del NIT ante la DIAN."),
            ("Nombramiento del representante legal", "Y de suplente o junta directiva si los necesitas."),
            ("Acompañamiento para la cuenta bancaria", "Te guiamos con los documentos que pide el banco."),
            ("Checklist de obligaciones iniciales", "Libros, renovación de matrícula y fechas clave."),
        ],
        "includes_note": "Los costos de terceros —impuesto de registro departamental y derechos de inscripción de la Cámara de Comercio— no hacen parte de los honorarios. Te los informamos con precisión en la cotización.",
        "steps": [
            ("Consulta inicial", "Nos cuentas tu idea de negocio, quiénes serán los socios y cómo quieres organizarte. Te enviamos la cotización."),
            ("Recopilación de información", "Te pedimos documentos de identidad de los accionistas, nombre deseado, objeto social, capital y domicilio."),
            ("Redacción y revisión", "Preparamos los estatutos, verificamos la disponibilidad del nombre y ajustamos todo contigo antes de firmar."),
            ("Registro y entrega", "Radicamos ante la Cámara de Comercio, coordinamos el NIT y te entregamos el certificado de existencia y representación."),
        ],
        "timing": "Entre 5 y 10 días hábiles desde que recibimos la información completa. Los tiempos de la Cámara de Comercio y la DIAN pueden variar.",
        "faqs": [
            ("¿Cuánto cuesta constituir una SAS en Colombia?",
             ["El costo total tiene dos partes: nuestros honorarios, que son fijos y conoces antes de empezar, y los costos de terceros, que son el impuesto de registro (lo cobra el departamento y se calcula sobre el capital) y los derechos de inscripción y matrícula ante la Cámara de Comercio.",
              "Escríbenos por WhatsApp con el capital que tienes en mente y te enviamos una cotización con el desglose completo, sin sorpresas."]),
            ("¿Cuánto tiempo toma el proceso?",
             ["Normalmente entre 5 y 10 días hábiles desde que tenemos la información y las firmas. La mayor parte del tiempo depende de la Cámara de Comercio y de la asignación del NIT por parte de la DIAN."]),
            ("¿Necesito ir presencialmente a alguna parte?",
             ["No. Todo el proceso se puede hacer de forma digital: firmas electrónicas, radicación virtual y entrega de documentos por correo. Si prefieres firmar en persona, te recibimos en Rionegro."]),
            ("¿Qué documentos necesito para empezar?",
             ["Copia del documento de identidad de cada accionista y del representante legal, el nombre que quieres para la empresa (con dos o tres alternativas), una descripción de la actividad, el capital y la dirección del domicilio. Si un accionista es una empresa, también su certificado de existencia y representación."]),
            ("¿Puedo tener socios extranjeros?",
             ["Sí. Una SAS puede tener accionistas extranjeros, personas naturales o empresas. Necesitarán su pasaporte o documentos apostillados, según el caso, y su aporte de capital debe registrarse como inversión extranjera ante el Banco de la República. Te guiamos en cada paso."]),
            ("¿Hay un capital mínimo para constituir una SAS?",
             ["La ley no exige capital mínimo y el capital suscrito puede pagarse en un plazo de hasta dos años. Aun así, te recomendamos definir un capital coherente con tu operación: bancos, proveedores y licitaciones suelen revisarlo."]),
            ("¿La SAS es la mejor figura para mi negocio?",
             ["En la mayoría de los casos sí, por su flexibilidad y responsabilidad limitada. Pero si tu actividad está regulada (por ejemplo, ciertas actividades financieras) o si buscas otra estructura, te lo diremos en la consulta inicial antes de cobrarte un peso."]),
        ],
        "related": ["contratos", "propiedad-intelectual", "gobierno-corporativo"],
        "cta_title": "¿Listo para constituir tu empresa?",
        "cta_text": "Escríbenos y recibe tu cotización con tarifa fija en menos de 24 horas.",
    },
    # ------------------------------------------------------------ Contratos
    {
        "slug": "contratos",
        "cat": "empresas",
        "icon": "file",
        "name": "Contratos comerciales",
        "nav_desc": "Redacción y revisión a la medida",
        "short": "Contratos a la medida: servicios, distribución, confidencialidad y más.",
        "long": "Redactamos y revisamos los contratos que sostienen tu negocio, con cláusulas que te protegen de verdad cuando algo no sale como se acordó.",
        "card_points": ["Redacción o revisión", "Una ronda de ajustes incluida", "Entrega en Word y PDF"],
        "h1": "Contratos comerciales",
        "h1_sub": "Acuerdos claros que protegen tu negocio",
        "intro": "Un buen contrato evita el 90 % de los conflictos antes de que ocurran. Redactamos, revisamos y negociamos contratos adaptados a tu operación real, con un lenguaje que tú y tu contraparte entienden.",
        "delivery": "3–7 días hábiles",
        "ideal": "Empresas que venden servicios, distribuyen productos, comparten información sensible o firman con proveedores y aliados.",
        "wa": "contratos comerciales",
        "meta_title": "Abogado para contratos comerciales en Colombia | GC Legal",
        "meta_desc": "Redacción y revisión de contratos de prestación de servicios, distribución, suministro, NDA, licencias, franquicias y arrendamiento comercial. Tarifa fija y entrega en 3 a 7 días.",
        "what_title": "¿Por qué necesitas un contrato hecho a la medida?",
        "what": [
            "Los modelos que circulan en internet no conocen tu negocio. Suelen omitir lo que de verdad importa: cómo se miden los entregables, qué pasa si te pagan tarde, quién es dueño de lo que se crea o cómo se termina la relación sin quedar expuesto.",
            "En Colombia, el Código de Comercio y el Código Civil llenan los vacíos que deja un contrato, y no siempre a tu favor. Un contrato bien redactado define las reglas que tú eliges: cláusulas penales, plazos, garantías, confidencialidad y mecanismos para resolver disputas sin años de pleito.",
            "Te ayudamos tanto si necesitas un contrato desde cero como si la otra parte ya te envió el suyo y quieres saber qué estás firmando.",
        ],
        "extra": {
            "title": "Contratos que redactamos con frecuencia",
            "chips": ["Prestación de servicios", "Distribución", "Suministro", "Confidencialidad (NDA)", "Licencia de uso", "Franquicia", "Arrendamiento comercial", "Términos y condiciones", "Joint venture", "Acuerdo de accionistas", "Compraventa comercial", "Agencia comercial"],
        },
        "includes": [
            ("Consulta inicial sobre tu operación", "Entendemos el negocio antes de escribir una sola cláusula."),
            ("Redacción del contrato personalizado", "O revisión con comentarios si ya tienes un borrador."),
            ("Cláusulas de protección clave", "Penalidades, garantías, terminación y solución de conflictos."),
            ("Una ronda de revisión y ajustes", "Incorporamos tus comentarios o los de tu contraparte."),
            ("Entrega en Word y PDF", "Listo para firma física o electrónica."),
            ("Explicación de los puntos críticos", "Sabrás exactamente qué estás firmando y por qué."),
        ],
        "includes_note": "Negociaciones extensas con la contraparte, rondas adicionales o contratos de alta complejidad (por ejemplo, internacionales) se cotizan por separado antes de empezar.",
        "steps": [
            ("Consulta inicial", "Nos cuentas qué tipo de contrato necesitas, con quién lo firmarás y qué te preocupa. Te enviamos la cotización."),
            ("Información del negocio", "Recibimos datos de las partes, condiciones comerciales y, si existe, el borrador actual."),
            ("Redacción y revisión", "Preparamos el contrato o el informe de revisión y lo ajustamos contigo en una ronda de comentarios."),
            ("Entrega final", "Recibes la versión final en Word y PDF, lista para firmar."),
        ],
        "timing": "Entre 3 y 7 días hábiles según la complejidad del contrato. Para urgencias, pregúntanos por entrega prioritaria.",
        "faqs": [
            ("¿Hay alguna diferencia entre un contrato y un acuerdo?",
             ["En la práctica, no. Para la ley colombiana un contrato es un acuerdo de voluntades que crea obligaciones; el nombre del documento (acuerdo, convenio, carta de intención) no cambia sus efectos. Lo que importa es su contenido y que las partes tengan la intención de obligarse."]),
            ("¿Cuándo necesito un abogado para un contrato?",
             ["Siempre que el contrato involucre dinero importante, una relación de largo plazo, propiedad intelectual, información confidencial o exclusividad. También cuando la otra parte te envía su propio modelo: suele estar escrito para protegerla a ella."]),
            ("¿Qué pasa si la otra parte no cumple?",
             ["Depende de lo que diga el contrato. Si tiene cláusula penal, puedes exigirla; si el documento presta mérito ejecutivo, puedes iniciar un proceso ejecutivo, que es más rápido. Si pactaron conciliación o arbitraje, ese es el camino. Por eso es clave redactar estas cláusulas antes de que exista el problema."]),
            ("¿Puedo usar un modelo genérico de internet?",
             ["Puedes, pero corres riesgos: modelos de otros países que no aplican en Colombia, cláusulas contradictorias o vacíos justo en los puntos que generan conflicto. Una revisión profesional cuesta mucho menos que un pleito."]),
            ("¿Revisan contratos que me envía la otra parte?",
             ["Sí. Te entregamos el contrato con comentarios y cambios sugeridos, y te explicamos qué cláusulas son negociables y cuáles son un riesgo real."]),
            ("¿Los contratos se tienen que autenticar en notaría?",
             ["En general, no. La mayoría de los contratos comerciales son válidos con la firma de las partes, y la firma electrónica tiene plena validez en Colombia (Ley 527 de 1999). Algunos actos sí exigen solemnidades especiales, como la compraventa de inmuebles; te lo indicamos cuando aplique."]),
        ],
        "related": ["asesoria-empresarial", "constitucion-sas", "propiedad-intelectual"],
        "cta_title": "¿Listo para firmar con tranquilidad?",
        "cta_text": "Cuéntanos qué contrato necesitas y recibe tu cotización en menos de 24 horas.",
    },
    # ------------------------------------------------------------ Asesoría
    {
        "slug": "asesoria-empresarial",
        "cat": "empresas",
        "icon": "briefcase",
        "name": "Asesoría jurídica empresarial",
        "nav_desc": "Tu abogado de cabecera, plan mensual",
        "short": "Acompañamiento legal recurrente para tu empresa, cuando lo necesites.",
        "long": "Un equipo jurídico disponible para tu empresa con un plan mensual de tarifa fija: consultas, revisión de contratos y alertas de cumplimiento, sin contratar un abogado de planta.",
        "card_points": ["Consultas por WhatsApp y videollamada", "Revisión de contratos y documentos", "Tarifa mensual fija"],
        "h1": "Asesoría jurídica empresarial",
        "h1_sub": "Tu abogado de cabecera, sin nómina",
        "intro": "Las dudas legales no esperan a que tengas presupuesto para un abogado. Con nuestro plan de asesoría mensual tienes un equipo jurídico que conoce tu empresa y responde cuando lo necesitas, por una tarifa fija.",
        "delivery": "Plan mensual",
        "delivery_label": "Modalidad",
        "badge2": "Respuesta en 24 h hábiles",
        "ideal": "Pymes y empresas en crecimiento que toman decisiones a diario y necesitan criterio jurídico sin crear un área legal.",
        "wa": "los planes de asesoría jurídica empresarial",
        "meta_title": "Asesoría jurídica empresarial mensual con tarifa fija | GC Legal",
        "meta_desc": "Plan de asesoría legal recurrente para empresas en Colombia: consultas por WhatsApp y videollamada, revisión de contratos, alertas de cumplimiento y tarifas preferenciales.",
        "what_title": "¿Qué es la asesoría jurídica recurrente?",
        "what": [
            "La mayoría de las empresas llama a un abogado cuando el problema ya existe: un cliente que no paga, una sanción, un socio inconforme. A esa altura, todo es más caro y más lento.",
            "Con un plan de asesoría mensual, el abogado está presente <strong>antes</strong> de que las cosas se compliquen. Revisas el contrato antes de firmarlo, consultas la decisión antes de tomarla y te enteras de una nueva obligación antes de que venza.",
            "Funciona como tener un área legal propia, pero sin el costo de un salario, prestaciones y seguridad social. Pagas una tarifa fija al mes y sabes exactamente qué incluye.",
        ],
        "plans": [
            {"name": "Esencial", "for": "Emprendimientos y microempresas que necesitan resolver dudas puntuales con respaldo profesional.",
             "points": ["Consultas por WhatsApp y correo", "Revisión de documentos cortos", "Alertas de vencimientos societarios", "Tarifa preferencial en proyectos"]},
            {"name": "Empresarial", "featured": True, "for": "Pymes con operación activa, varios contratos al mes y decisiones frecuentes.",
             "points": ["Todo lo del plan Esencial", "Videollamada mensual de seguimiento", "Revisión de contratos incluida", "Actas y documentos corporativos básicos"]},
            {"name": "Corporativo", "for": "Empresas con estructura de socios, junta directiva o necesidades jurídicas recurrentes.",
             "points": ["Todo lo del plan Empresarial", "Acompañamiento en reuniones de socios", "Revisión de cumplimiento en datos personales", "Atención prioritaria"]},
        ],
        "includes": [
            ("Consultas jurídicas por WhatsApp y videollamada", "Dentro de los parámetros definidos en tu plan."),
            ("Revisión de contratos y documentos", "Antes de firmar, no después."),
            ("Acompañamiento en decisiones corporativas", "Socios, nombramientos, inversiones y reorganizaciones."),
            ("Alertas de cumplimiento", "Renovación de matrícula, asamblea anual, datos personales y más."),
            ("Tarifas preferenciales", "Descuento en proyectos adicionales fuera del plan."),
            ("Un equipo que conoce tu empresa", "No tienes que explicar todo desde cero cada vez."),
        ],
        "includes_note": "Los litigios, procesos judiciales y proyectos de gran alcance (por ejemplo, una reorganización societaria completa) no están incluidos en el plan; se cotizan aparte con tarifa preferencial.",
        "steps": [
            ("Diagnóstico inicial", "Conversamos sobre tu empresa, tus contratos y tus principales riesgos. Sin costo."),
            ("Propuesta de plan", "Te recomendamos el nivel adecuado y te enviamos el alcance y la tarifa mensual."),
            ("Puesta en marcha", "Revisamos tus documentos clave y configuramos tu calendario de obligaciones."),
            ("Acompañamiento continuo", "Consultas cuando las necesites y seguimiento periódico de tu situación jurídica."),
        ],
        "timing": "Puedes empezar en menos de una semana. Respondemos las consultas en menos de 24 horas hábiles.",
        "faqs": [
            ("¿Qué incluye y qué no incluye el plan?",
             ["Incluye consultas jurídicas del día a día de tu empresa —comerciales, societarias, contractuales y de datos personales—, revisión de documentos y alertas de cumplimiento, según el nivel del plan. No incluye litigios ni proyectos de gran alcance, que cotizamos aparte con tarifa preferencial. Todo queda escrito en tu propuesta."]),
            ("¿Puedo cancelar el plan?",
             ["Sí. Los planes se pactan mes a mes y las condiciones de terminación quedan claras en la propuesta antes de firmar. Queremos que te quedes porque te sirve, no porque estés amarrado."]),
            ("¿Qué pasa si tengo una urgencia?",
             ["Escríbenos por WhatsApp indicando que es urgente. Los clientes con plan tienen prioridad en la atención y, si el asunto requiere trabajo adicional, te decimos el costo antes de hacerlo."]),
            ("¿En qué se diferencia de contratar un abogado de planta?",
             ["Un abogado interno implica salario, prestaciones sociales, seguridad social y, aun así, una sola persona con una sola especialidad. Con el plan accedes a un equipo con experiencia en distintas áreas, por una fracción del costo y sin cargas laborales."]),
            ("¿Cubre temas laborales y tributarios?",
             ["Te orientamos en las preguntas laborales y tributarias frecuentes de una empresa. Si el asunto requiere un especialista o un proceso, te lo decimos y lo coordinamos con tarifa preferencial."]),
        ],
        "related": ["contratos", "gobierno-corporativo", "proteccion-datos"],
        "cta_title": "¿Listo para tener un abogado de cabecera?",
        "cta_text": "Agenda un diagnóstico sin costo y recibe la propuesta de plan en menos de 24 horas.",
    },
    # --------------------------------------------------------------- Marcas
    {
        "slug": "propiedad-intelectual",
        "cat": "empresas",
        "icon": "shield",
        "name": "Registro de marcas",
        "full_name": "Registro de marcas y propiedad intelectual",
        "nav_desc": "Protege tu marca ante la SIC",
        "short": "Protege tu marca ante la SIC. Trámite completo con seguimiento.",
        "long": "Búsqueda de antecedentes, solicitud de registro ante la Superintendencia de Industria y Comercio y seguimiento hasta la decisión final.",
        "card_points": ["Búsqueda de antecedentes", "Radicación ante la SIC", "Seguimiento hasta la resolución"],
        "h1": "Registro de marcas",
        "h1_sub": "Protege lo que te hace único",
        "intro": "Tu marca es uno de los activos más valiosos de tu empresa, pero solo te pertenece si está registrada. Hacemos la búsqueda de antecedentes, presentamos la solicitud ante la SIC y la vigilamos hasta que obtengas tu registro.",
        "delivery": "Radicación en 3–5 días hábiles",
        "ideal": "Emprendimientos que lanzan una marca, empresas que se expanden y creadores que quieren proteger su nombre o logo.",
        "wa": "el registro de una marca",
        "meta_title": "Registro de marca en Colombia ante la SIC | GC Legal",
        "meta_desc": "Registra tu marca en Colombia: búsqueda de antecedentes, clasificación de Niza, radicación ante la SIC y seguimiento hasta la resolución. Tarifa fija de honorarios.",
        "what_title": "¿Por qué registrar tu marca?",
        "what": [
            "En Colombia, el derecho exclusivo sobre una marca se adquiere con el registro ante la <strong>Superintendencia de Industria y Comercio (SIC)</strong>, no con el uso. Si otra persona registra primero tu nombre o tu logo, puede impedirte usarlo, aunque tú lo hayas creado.",
            "Tampoco basta con tener la razón social inscrita en la Cámara de Comercio: eso identifica a la empresa, pero no protege la marca con la que vendes tus productos o servicios.",
            "Antes de radicar, hacemos una búsqueda de antecedentes para saber si tu marca tiene posibilidades reales de registro. Así evitas invertir en una solicitud que será negada o en un logo que tendrás que cambiar.",
        ],
        "includes": [
            ("Búsqueda de antecedentes marcarios", "Analizamos marcas idénticas o similares ya registradas."),
            ("Concepto de registrabilidad", "Te decimos con franqueza las probabilidades de éxito."),
            ("Clasificación de Niza", "Identificamos las clases de productos y servicios que debes proteger."),
            ("Preparación y radicación de la solicitud", "Marca nominativa, figurativa o mixta."),
            ("Seguimiento del trámite", "Publicación en la Gaceta, oposiciones y requerimientos."),
            ("Reporte hasta la resolución", "Te avisamos en cada etapa hasta la decisión de la SIC."),
        ],
        "includes_note": "Las tasas oficiales de la SIC se pagan aparte y dependen del número de clases. Responder oposiciones, recursos o requerimientos de fondo se cotiza por separado si llega a ser necesario. También asesoramos registros de obras y software ante la Dirección Nacional de Derecho de Autor.",
        "steps": [
            ("Consulta inicial", "Nos cuentas cuál es tu marca, qué vendes y dónde. Te enviamos la cotización."),
            ("Búsqueda y concepto", "Revisamos antecedentes y te entregamos un concepto de viabilidad con recomendaciones."),
            ("Radicación ante la SIC", "Preparamos y presentamos la solicitud en las clases correctas."),
            ("Seguimiento y resolución", "Vigilamos la publicación, el plazo de oposiciones y el examen de fondo hasta la decisión."),
        ],
        "timing": "La búsqueda y la radicación toman de 3 a 5 días hábiles. El trámite ante la SIC suele durar varios meses (alrededor de seis a ocho si no hay oposiciones).",
        "faqs": [
            ("¿Cuánto cuesta registrar una marca en Colombia?",
             ["Hay dos componentes: nuestros honorarios, que son fijos, y la tasa oficial de la SIC, que se actualiza cada año y se paga por cada clase en la que registres la marca. Existen descuentos en la tasa para algunas Mipymes y personas naturales que cumplen requisitos. Te enviamos la cotización completa con ambos valores."]),
            ("¿Cuánto dura el trámite?",
             ["Si no hay oposiciones ni requerimientos, el trámite suele tomar entre seis y ocho meses. La solicitud se publica en la Gaceta de Propiedad Industrial y se abre un plazo de 30 días hábiles para que terceros se opongan; luego la SIC hace el examen de fondo y decide. El registro dura 10 años y es renovable."]),
            ("¿Qué pasa si me niegan el registro?",
             ["Puedes presentar recursos contra la decisión dentro del plazo legal. También es posible ajustar la marca o las clases y volver a solicitar. Por eso la búsqueda de antecedentes previa es tan importante: reduce mucho el riesgo de negación."]),
            ("¿Cuál es la diferencia entre marca, nombre comercial y razón social?",
             ["La razón social es el nombre legal de tu empresa ante la Cámara de Comercio. La marca distingue tus productos o servicios en el mercado y se protege con el registro ante la SIC. El nombre comercial identifica tu establecimiento o actividad. Pueden coincidir, pero cada uno se protege de forma distinta."]),
            ("¿Mi registro me protege en otros países?",
             ["No. El registro en Colombia protege tu marca en el territorio colombiano. Si planeas exportar o expandirte, puedes extender la protección a través del Protocolo de Madrid o directamente en cada país; además, tienes un derecho de prioridad de seis meses desde tu solicitud en Colombia."]),
            ("¿Qué es la clasificación de Niza?",
             ["Es el sistema internacional que agrupa productos y servicios en 45 clases. Tu marca se protege solo en las clases en las que la registres, por eso es clave elegirlas bien desde el principio."]),
        ],
        "related": ["constitucion-sas", "contratos", "proteccion-datos"],
        "cta_title": "¿Listo para proteger tu marca?",
        "cta_text": "Envíanos el nombre de tu marca y te decimos si está disponible. Cotización en menos de 24 horas.",
    },
    # ---------------------------------------------------------------- Datos
    {
        "slug": "proteccion-datos",
        "cat": "empresas",
        "icon": "lock",
        "name": "Protección de datos",
        "full_name": "Protección de datos y habeas data",
        "nav_desc": "Cumple la Ley 1581 de 2012",
        "short": "Cumple con la ley de habeas data. Políticas, avisos y manuales.",
        "long": "Diseñamos la política de tratamiento, avisos de privacidad, autorizaciones y el manual interno que tu empresa necesita para cumplir la Ley 1581 de 2012.",
        "card_points": ["Política de tratamiento de datos", "Aviso de privacidad y autorizaciones", "Registro en el RNBD si aplica"],
        "h1": "Protección de datos personales",
        "h1_sub": "Cumple la ley y genera confianza",
        "intro": "Si tu empresa recoge datos de clientes, empleados o proveedores —y casi todas lo hacen— debe cumplir el régimen de protección de datos personales. Te entregamos los documentos y procedimientos para hacerlo bien y evitar sanciones de la SIC.",
        "delivery": "5–10 días hábiles",
        "ideal": "Empresas con bases de datos de clientes, comercio electrónico, plataformas digitales, clínicas, colegios y empleadores.",
        "wa": "protección de datos personales",
        "meta_title": "Protección de datos personales y habeas data (Ley 1581) | GC Legal",
        "meta_desc": "Política de tratamiento de datos, aviso de privacidad, autorizaciones, manual interno y registro en el RNBD. Cumple la Ley 1581 de 2012 con tarifa fija.",
        "what_title": "¿Por qué tu empresa necesita cumplir con la protección de datos?",
        "what": [
            "La <strong>Ley 1581 de 2012</strong> y sus decretos reglamentarios obligan a toda empresa que recoja, almacene o use datos personales a tratarlos con autorización, para fines claros y con medidas de seguridad. Esto incluye la base de clientes, el formulario de tu página web y las hojas de vida de tus empleados.",
            "La Superintendencia de Industria y Comercio vigila el cumplimiento y puede imponer multas de hasta 2.000 salarios mínimos mensuales, además de suspender actividades. Más allá de la sanción, un mal manejo de datos afecta la confianza de tus clientes.",
            "Cumplir no es publicar una política copiada en la web. Implica saber qué datos tienes, para qué los usas, quién los maneja y cómo respondes cuando alguien pide conocerlos o eliminarlos. Te ayudamos a montar todo eso de forma práctica.",
        ],
        "includes": [
            ("Diagnóstico de tus bases de datos", "Qué datos recoges, de quién, para qué y dónde se guardan."),
            ("Política de tratamiento de datos", "Ajustada a tu operación real, lista para publicar."),
            ("Aviso de privacidad", "Para web, formularios y puntos de contacto."),
            ("Formatos de autorización", "Clientes, empleados, proveedores y datos sensibles."),
            ("Manual interno de procedimientos", "Consultas, reclamos, seguridad y responsables."),
            ("Cláusulas contractuales", "Para proveedores que manejan datos por ti (transmisión)."),
            ("Registro en el RNBD", "Si tu empresa está obligada a inscribir sus bases de datos."),
        ],
        "includes_note": "La implementación técnica de medidas de seguridad informática corresponde a tu equipo de tecnología o proveedor; nosotros definimos los requisitos jurídicos que debe cumplir.",
        "steps": [
            ("Consulta inicial", "Nos cuentas a qué se dedica tu empresa y qué datos manejas. Te enviamos la cotización."),
            ("Inventario de datos", "Completas un cuestionario guiado sobre tus bases de datos y procesos."),
            ("Documentos a la medida", "Redactamos la política, el aviso, las autorizaciones y el manual, y los revisamos contigo."),
            ("Entrega y registro", "Recibes todo listo para implementar y, si aplica, inscribimos tus bases en el RNBD."),
        ],
        "timing": "Entre 5 y 10 días hábiles desde que recibimos el cuestionario completo.",
        "faqs": [
            ("¿Qué empresas están obligadas a cumplir la ley de protección de datos?",
             ["Prácticamente todas. Cualquier empresa o persona que trate datos personales en Colombia —de clientes, empleados, proveedores o visitantes de su web— debe cumplir la Ley 1581 de 2012. Lo que cambia según el tamaño es, por ejemplo, la obligación de inscribirse en el RNBD."]),
            ("¿Cuáles son las multas por incumplimiento?",
             ["La SIC puede imponer multas de hasta 2.000 salarios mínimos mensuales legales vigentes, suspender las actividades relacionadas con el tratamiento de datos hasta por seis meses e incluso ordenar el cierre de esas operaciones. Las sanciones se gradúan según el daño y la reincidencia."]),
            ("¿Qué es el RNBD y debo inscribirme?",
             ["El Registro Nacional de Bases de Datos es administrado por la SIC. Hoy están obligadas a inscribirse las sociedades y entidades sin ánimo de lucro con activos totales superiores a 100.000 UVT, y las personas jurídicas de naturaleza pública. Revisamos si tu empresa está obligada y, si es así, hacemos la inscripción."]),
            ("¿Cómo debo pedir el consentimiento para tratar datos?",
             ["La autorización debe ser previa, expresa e informada: la persona debe saber qué datos recoges, para qué y cuáles son sus derechos. Puede darse por escrito, de forma verbal o mediante conductas inequívocas, pero tú debes poder probarla. Los datos sensibles y los de niños tienen reglas especiales."]),
            ("¿Puedo enviar datos a proveedores en otros países?",
             ["Sí, con reglas. Si el proveedor solo procesa los datos por tu cuenta (por ejemplo, un servicio en la nube), se trata de una transmisión y necesitas un contrato que lo regule. Si los entregas para que el tercero los use, es una transferencia internacional y el país de destino debe ofrecer un nivel adecuado de protección o aplicarse alguna excepción legal."]),
            ("¿Basta con publicar una política de privacidad en mi página web?",
             ["No. La política es solo una parte. También necesitas autorizaciones, un procedimiento para atender consultas y reclamos, un responsable interno y medidas de seguridad. La SIC evalúa que la política se cumpla en la práctica."]),
        ],
        "related": ["asesoria-empresarial", "contratos", "gobierno-corporativo"],
        "cta_title": "¿Listo para cumplir con la protección de datos?",
        "cta_text": "Cuéntanos qué datos maneja tu empresa y recibe tu cotización en menos de 24 horas.",
    },
    # ------------------------------------------------------------- Gobierno
    {
        "slug": "gobierno-corporativo",
        "cat": "empresas",
        "icon": "clipboard",
        "name": "Gobierno corporativo",
        "full_name": "Gobierno corporativo y actas societarias",
        "nav_desc": "Actas, reformas y libros al día",
        "short": "Actas, reformas estatutarias y cambios societarios sin enredos.",
        "long": "Preparamos actas de asamblea y junta, reformas estatutarias y cambios de representante legal, y los inscribimos en la Cámara de Comercio.",
        "card_points": ["Actas de asamblea y junta", "Reformas estatutarias", "Inscripción en Cámara de Comercio"],
        "h1": "Gobierno corporativo y actas societarias",
        "h1_sub": "Tu empresa en orden, por dentro",
        "intro": "Una sociedad con documentos desactualizados se frena justo cuando más necesita moverse: para pedir un crédito, entrar a una licitación o recibir un inversionista. Mantenemos tus actas, reformas y nombramientos al día y bien inscritos.",
        "delivery": "3–7 días hábiles",
        "ideal": "Sociedades que celebran su asamblea anual, cambian de representante legal, ajustan el capital o reciben nuevos socios.",
        "wa": "gobierno corporativo y actas societarias",
        "meta_title": "Actas de asamblea, reformas estatutarias y gobierno corporativo | GC Legal",
        "meta_desc": "Redacción de actas de asamblea y junta directiva, reformas estatutarias, cambio de representante legal e inscripción en Cámara de Comercio. Tarifa fija.",
        "what_title": "¿Por qué mantener tu documentación societaria al día?",
        "what": [
            "Las decisiones de una sociedad solo producen efectos frente a terceros cuando están bien documentadas y, en muchos casos, inscritas en la Cámara de Comercio. Un acta mal hecha puede ser rechazada, y un nombramiento sin inscribir deja a la empresa con un representante legal que, para los demás, no existe.",
            "El Código de Comercio y la Ley 222 de 1995 exigen además que los administradores actúen con diligencia y lealtad, y responden con su patrimonio cuando no lo hacen. Llevar las reuniones, libros y decisiones en regla es la mejor protección para la empresa y para quienes la dirigen.",
            "Nos encargamos de la parte formal —convocatorias, quórum, actas, reformas e inscripciones— para que las decisiones de tu empresa sean válidas y se puedan probar.",
        ],
        "includes": [
            ("Actas de asamblea y junta directiva", "Ordinarias, extraordinarias y no presenciales."),
            ("Convocatorias y orden del día", "Con los plazos y requisitos de tus estatutos."),
            ("Reformas estatutarias", "Objeto social, capital, órganos, domicilio y más."),
            ("Cambio de representante legal", "Nombramiento, aceptación e inscripción."),
            ("Inscripción en la Cámara de Comercio", "Radicación y seguimiento hasta el registro."),
            ("Asesoría sobre obligaciones societarias", "Libros, asamblea anual y renovación de matrícula."),
        ],
        "includes_note": "Los derechos de inscripción de la Cámara de Comercio y, si aplica, los gastos notariales no hacen parte de los honorarios.",
        "steps": [
            ("Consulta inicial", "Nos cuentas qué decisión necesita tomar o formalizar tu empresa. Te enviamos la cotización."),
            ("Revisión de estatutos", "Verificamos quién debe decidir, con qué quórum y cómo debe convocarse."),
            ("Preparación de documentos", "Redactamos convocatoria, acta y reforma, y te acompañamos en la reunión si lo necesitas."),
            ("Inscripción y entrega", "Radicamos en la Cámara de Comercio y te entregamos el certificado actualizado."),
        ],
        "timing": "Entre 3 y 7 días hábiles según el documento. La inscripción depende de los tiempos de la Cámara de Comercio.",
        "faqs": [
            ("¿Cada cuánto se debe reunir la asamblea de accionistas?",
             ["Por regla general, al menos una vez al año en reunión ordinaria, dentro de los tres primeros meses, para aprobar los estados financieros y tomar las decisiones del ejercicio, salvo que los estatutos fijen otra fecha. Además puede reunirse de forma extraordinaria cuando sea necesario."]),
            ("¿Qué reformas requieren escritura pública?",
             ["En las SAS, las reformas estatutarias se hacen por documento privado inscrito en la Cámara de Comercio, salvo que impliquen el aporte o la transferencia de bienes que exigen escritura, como inmuebles. En otros tipos de sociedad, como la limitada o la anónima, la regla general es la escritura pública."]),
            ("¿Qué responsabilidad tienen los administradores?",
             ["Los administradores —representante legal, miembros de junta y gerentes— deben obrar de buena fe, con lealtad y con la diligencia de un buen hombre de negocios. Si causan perjuicios a la sociedad, a los socios o a terceros por dolo o culpa, responden solidaria e ilimitadamente (Ley 222 de 1995)."]),
            ("¿Cómo cambio de representante legal?",
             ["El órgano competente según tus estatutos (normalmente la asamblea o la junta directiva) aprueba el nombramiento en un acta, la persona acepta el cargo y se inscribe en la Cámara de Comercio. Hasta que se inscribe, frente a terceros sigue figurando el representante anterior."]),
            ("¿Las reuniones pueden ser virtuales?",
             ["Sí. La ley colombiana permite reuniones no presenciales y mixtas, siempre que se pueda probar la participación de los asistentes y se cumplan las reglas de quórum y mayorías. Te ayudamos a documentarlas correctamente."]),
            ("¿Qué pasa si no tengo los libros y actas al día?",
             ["Las decisiones que no constan en actas son difíciles de probar y la Cámara de Comercio puede negar inscripciones. Además, recuerda que la matrícula mercantil debe renovarse cada año antes del 31 de marzo. Podemos ayudarte a ponerte al día."]),
        ],
        "related": ["constitucion-sas", "asesoria-empresarial", "contratos"],
        "cta_title": "¿Listo para poner tu empresa en orden?",
        "cta_text": "Cuéntanos qué necesitas formalizar y recibe tu cotización en menos de 24 horas.",
    },
    # -------------------------------------------------------------- Familia
    {
        "slug": "derecho-familia",
        "cat": "personas",
        "icon": "users",
        "name": "Derecho de familia",
        "nav_desc": "Divorcios, custodia y alimentos",
        "short": "Divorcios, liquidaciones de sociedad conyugal y acuerdos familiares.",
        "long": "Acompañamiento legal cercano y reservado en divorcios, liquidación de sociedad conyugal, custodia y cuota de alimentos, por vía notarial o judicial.",
        "card_points": ["Divorcio notarial o judicial", "Liquidación de sociedad conyugal", "Custodia y alimentos"],
        "h1": "Derecho de familia",
        "h1_sub": "Seguridad jurídica en los momentos difíciles",
        "intro": "Un divorcio o un acuerdo sobre los hijos ya es suficientemente difícil sin la incertidumbre legal. Te explicamos tus opciones con claridad, buscamos acuerdos cuando es posible y te representamos con firmeza cuando no lo es.",
        "delivery": "Tarifa fija en trámites notariales",
        "delivery_label": "Tarifa",
        "badge2": "Atención reservada",
        "ideal": "Parejas que quieren divorciarse de mutuo acuerdo, personas que necesitan liquidar bienes o fijar custodia y alimentos.",
        "wa": "derecho de familia",
        "meta_title": "Abogado de familia en Rionegro: divorcios, custodia y alimentos | GC Legal",
        "meta_desc": "Divorcio notarial y judicial, liquidación de sociedad conyugal, custodia y cuota de alimentos. Asesoría reservada en Rionegro, Antioquia, y atención digital en toda Colombia.",
        "what_title": "¿Cómo te ayudamos en asuntos de familia?",
        "what": [
            "Las decisiones que tomas en un proceso de familia —cómo se reparten los bienes, con quién viven los hijos, cuánto se aporta para su manutención— te acompañan por años. Tomarlas con información clara marca la diferencia.",
            "Cuando hay acuerdo, el camino suele ser más corto: el <strong>divorcio de mutuo acuerdo</strong> y la liquidación de la sociedad conyugal pueden hacerse ante notario, en pocas semanas. Cuando no lo hay, te representamos en el proceso judicial y buscamos la mejor salida posible.",
            "Siempre ponemos en primer lugar el bienestar de los hijos y la tranquilidad de la familia. Nuestro trabajo es reducir el conflicto, no alimentarlo.",
        ],
        "extra": {
            "title": "Asuntos que atendemos",
            "chips": ["Divorcio de mutuo acuerdo", "Divorcio contencioso", "Cesación de efectos civiles de matrimonio religioso", "Liquidación de sociedad conyugal", "Disolución de unión marital de hecho", "Custodia y cuidado personal", "Régimen de visitas", "Cuota de alimentos", "Capitulaciones"],
        },
        "includes": [
            ("Asesoría inicial", "Análisis de tu situación y de los caminos posibles."),
            ("Estrategia y propuesta de acuerdo", "Bienes, custodia, visitas y alimentos."),
            ("Preparación de documentos", "Poder, acuerdo, inventario de bienes y solicitud."),
            ("Trámite notarial", "Radicación y acompañamiento hasta la escritura."),
            ("Representación judicial", "Cuando no hay acuerdo o la ley exige el proceso."),
            ("Orientación sobre los efectos del acuerdo", "Qué cambia en tus bienes, tu apellido y tus obligaciones."),
        ],
        "includes_note": "Los trámites notariales se cotizan con tarifa fija. Los procesos judiciales tienen costos y tiempos variables y se cotizan de forma individual después de analizar el caso. Los derechos notariales y gastos del proceso no hacen parte de los honorarios.",
        "steps": [
            ("Consulta inicial", "Conversamos en un espacio reservado sobre tu situación y tus prioridades."),
            ("Análisis y propuesta", "Te explicamos si el caso puede ir por notaría o requiere juez, y te enviamos la cotización."),
            ("Documentos y acuerdos", "Recopilamos los registros civiles y bienes, y preparamos el acuerdo o la demanda."),
            ("Trámite y cierre", "Radicamos ante la notaría o el juzgado y te acompañamos hasta la escritura o la sentencia."),
        ],
        "timing": "Un divorcio notarial de mutuo acuerdo suele resolverse en pocas semanas. Los procesos judiciales pueden tardar meses, según el despacho y la complejidad.",
        "faqs": [
            ("¿Cuál es la diferencia entre el divorcio notarial y el judicial?",
             ["El divorcio notarial solo es posible cuando ambos cónyuges están de acuerdo en divorciarse y en las condiciones (bienes, hijos, alimentos). Es más rápido y se hace mediante escritura pública. El judicial se tramita ante un juez de familia cuando no hay acuerdo o cuando se invoca una causal legal."]),
            ("¿Me puedo divorciar si mi pareja no está de acuerdo?",
             ["Sí, por vía judicial. Desde la Ley 2442 de 2024, la sola voluntad de uno de los cónyuges es causal de divorcio, lo que permite terminar el vínculo sin tener que probar culpas. Te explicamos cómo funciona en tu caso."]),
            ("¿Cuánto tarda un divorcio?",
             ["El divorcio notarial de mutuo acuerdo suele tardar pocas semanas desde que se radican los documentos. El judicial puede tardar varios meses o más, según el juzgado, la carga de trabajo y si hay controversia sobre bienes o hijos."]),
            ("¿Qué documentos necesito?",
             ["Registro civil de matrimonio, registros civiles de nacimiento de los cónyuges y de los hijos, documentos de identidad y, si van a liquidar la sociedad conyugal, el inventario de bienes y deudas con sus soportes. Te enviamos una lista exacta para tu caso."]),
            ("¿Existe la custodia compartida en Colombia?",
             ["Sí. Los padres pueden acordar una custodia compartida y, a falta de acuerdo, el juez decide siempre según el interés superior de los niños. Lo importante es que el acuerdo sea realista con las rutinas, el colegio y la cercanía de los hogares."]),
            ("¿Cómo se fija la cuota de alimentos?",
             ["Se tiene en cuenta la capacidad económica de quien paga y las necesidades de los hijos. Puede fijarse por acuerdo conciliado (ante comisaría de familia, ICBF, centro de conciliación o notaría) o por decisión de un juez. Si no se prueba el ingreso de quien paga, la ley presume que devenga al menos un salario mínimo."]),
        ],
        "related": ["acciones-constitucionales"],
        "related_extra": ["constitucion-sas"],
        "cta_title": "¿Listo para dar el siguiente paso con tranquilidad?",
        "cta_text": "Escríbenos con total reserva y recibe orientación y cotización en menos de 24 horas.",
    },
    # ----------------------------------------------------------- Tutelas
    {
        "slug": "acciones-constitucionales",
        "cat": "personas",
        "icon": "scale",
        "name": "Acciones constitucionales",
        "nav_desc": "Tutelas y acciones de cumplimiento",
        "short": "Tutelas y acciones de cumplimiento para proteger tus derechos.",
        "long": "Interponemos acciones de tutela y de cumplimiento cuando una entidad o un particular vulnera tus derechos fundamentales, y hacemos seguimiento hasta que el fallo se cumpla.",
        "card_points": ["Análisis del caso", "Redacción y radicación", "Seguimiento del fallo e impugnación"],
        "h1": "Acciones constitucionales",
        "h1_sub": "Protección inmediata de tus derechos",
        "intro": "Cuando una EPS niega un tratamiento, una entidad no responde tus peticiones o se vulnera tu debido proceso, la tutela es la herramienta para exigir protección rápida. La preparamos con argumentos sólidos para que el juez falle a tu favor.",
        "delivery": "Fallo en 10 días hábiles",
        "delivery_label": "Plazo del juez",
        "badge2": "Tarifa fija",
        "ideal": "Personas a quienes una EPS, una entidad pública o una empresa de servicios públicos les está vulnerando un derecho fundamental.",
        "wa": "una acción de tutela",
        "meta_title": "Abogado para tutelas y acciones constitucionales | GC Legal",
        "meta_desc": "Redacción y radicación de acciones de tutela y de cumplimiento: salud, derecho de petición, debido proceso, mínimo vital. Seguimiento del fallo, impugnación y desacato.",
        "what_title": "¿Qué es una acción de tutela y cuándo usarla?",
        "what": [
            "La <strong>acción de tutela</strong> (artículo 86 de la Constitución) es un mecanismo para que un juez proteja de forma inmediata tus derechos fundamentales cuando una autoridad pública —o, en ciertos casos, un particular— los vulnera o los pone en riesgo. El juez debe decidir en un plazo máximo de 10 días hábiles.",
            "Aunque la ley permite presentarla sin abogado, una tutela mal planteada se niega con frecuencia: por no demostrar la urgencia, por existir otro medio judicial o por no aportar las pruebas correctas. Nosotros analizamos si procede y construimos el caso para que tenga las mejores posibilidades.",
            "También interponemos la <strong>acción de cumplimiento</strong>, para exigir que una autoridad cumpla una ley o un acto administrativo, y te acompañamos en la impugnación y el incidente de desacato si el fallo no se cumple.",
        ],
        "includes": [
            ("Análisis de procedencia", "Te decimos con franqueza si la tutela es el camino correcto."),
            ("Derecho de petición previo", "Si hace falta agotar este paso antes de la tutela."),
            ("Redacción de la acción", "Hechos, derechos vulnerados, pruebas y pretensiones."),
            ("Radicación ante el juez competente", "Por canales digitales, sin que tengas que desplazarte."),
            ("Seguimiento del fallo", "Te informamos de cada actuación del juzgado."),
            ("Impugnación o desacato", "Si el fallo es desfavorable o no se cumple (según cotización)."),
        ],
        "includes_note": "La tutela tiene plazos constitucionales: el juez debe fallar en un máximo de 10 días hábiles. La impugnación debe presentarse dentro de los 3 días siguientes a la notificación del fallo.",
        "steps": [
            ("Consulta inicial", "Nos cuentas qué derecho se está vulnerando y quién lo está haciendo. Revisamos tus documentos."),
            ("Análisis y propuesta", "Confirmamos si procede la tutela u otra acción y te enviamos la cotización."),
            ("Redacción y radicación", "Preparamos la acción con las pruebas y la radicamos ante el juez competente."),
            ("Seguimiento y cumplimiento", "Vigilamos el fallo y, si es necesario, impugnamos o promovemos el desacato."),
        ],
        "timing": "Radicamos la tutela en 2 a 3 días hábiles desde que tenemos la información. El juez tiene hasta 10 días hábiles para fallar.",
        "faqs": [
            ("¿Cuándo procede una tutela?",
             ["Cuando se vulnera o amenaza un derecho fundamental y no existe otro mecanismo judicial eficaz para protegerlo, o cuando, aun existiendo, se necesita evitar un perjuicio irremediable. Además, debe presentarse en un tiempo razonable desde que ocurrió la vulneración."]),
            ("¿Contra quién se puede interponer?",
             ["Contra cualquier autoridad pública y, en algunos casos, contra particulares: quienes prestan servicios públicos (como las EPS o las empresas de servicios públicos domiciliarios) y aquellos frente a quienes estás en situación de subordinación o indefensión."]),
            ("¿Qué derechos protege?",
             ["Los derechos fundamentales, como la salud (en conexidad o de forma autónoma), el derecho de petición, el debido proceso, el mínimo vital, la educación, la igualdad, la intimidad, el habeas data y el trabajo, entre otros."]),
            ("¿Necesito un abogado para presentar una tutela?",
             ["No es obligatorio, pero sí recomendable. Muchas tutelas se niegan por problemas de forma o de prueba que un abogado detecta desde el principio. Si tu caso es sencillo, te lo diremos con honestidad."]),
            ("¿Qué pasa si me niegan la tutela?",
             ["Puedes impugnar el fallo dentro de los 3 días siguientes a su notificación. El juez de segunda instancia tiene 20 días para decidir. Después, el expediente se envía a la Corte Constitucional, que puede seleccionarlo para revisión."]),
            ("¿Y si me dan la razón pero no cumplen el fallo?",
             ["Se puede promover un incidente de desacato. El juez puede sancionar al responsable con arresto de hasta seis meses y multa de hasta 20 salarios mínimos, además de exigir el cumplimiento de la orden."]),
        ],
        "related": ["derecho-familia"],
        "related_extra": ["proteccion-datos"],
        "cta_title": "¿Están vulnerando tus derechos?",
        "cta_text": "Escríbenos hoy. Analizamos tu caso y te enviamos la cotización en menos de 24 horas.",
    },
]

SERVICE_BY_SLUG = {s["slug"]: s for s in SERVICES}

# --------------------------------------------------------------------------
# Home / páginas generales
# --------------------------------------------------------------------------
VALUE_PROPS = [
    ("scale", "Abogados expertos", "Profesionales con experiencia real en derecho empresarial, societario y de familia."),
    ("tag", "Tarifas claras y fijas", "Sabes exactamente cuánto pagas antes de empezar. Sin costos ocultos, sin facturación por horas."),
    ("laptop", "Proceso 100 % digital", "Inicia, gestiona y recibe tus documentos sin salir de tu oficina. Atención presencial cuando la necesites."),
]

HOW_STEPS = [
    ("chat", "Cuéntanos tu caso", "Escríbenos por WhatsApp o llena el formulario. Te respondemos en menos de 24 horas con una cotización clara."),
    ("doc", "Recibe tu propuesta", "Te enviamos el alcance, el plazo y la tarifa fija. Sin sorpresas. Aceptas en línea."),
    ("check-circle", "Recibe tu solución", "Tu abogado trabaja en tu caso. Recibes tus documentos listos y revisados."),
]

WHY = [
    ("tag", "Sin cobros por hora", "Nuestros honorarios son fijos y los conoces antes de empezar. Así tomas decisiones con claridad."),
    ("briefcase", "Experiencia empresarial real", "Conocemos el mundo corporativo por dentro. Asesoramos desde la constitución hasta la operación diaria."),
    ("pin", "Digital cuando quieras, presencial cuando necesites", "Trabaja con nosotros desde cualquier lugar de Colombia, o reúnete en persona en Rionegro."),
    ("zap", "Respuesta rápida", "Respondemos en menos de 24 horas. Tu tiempo importa tanto como el nuestro."),
]

HOW_DETAILED = [
    {
        "icon": "chat",
        "title": "Cuéntanos tu caso",
        "text": "Escríbenos por WhatsApp o desde el formulario de contacto. No necesitas saber el nombre técnico de lo que necesitas: cuéntanos la situación con tus palabras.",
        "points": [("Tú haces", "un mensaje con lo esencial y, si los tienes, documentos de soporte."),
                   ("Nosotros", "revisamos el caso y te hacemos las preguntas necesarias."),
                   ("Tiempo", "respuesta en menos de 24 horas hábiles.")],
    },
    {
        "icon": "doc",
        "title": "Recibe tu propuesta",
        "text": "Te enviamos una propuesta escrita con el alcance exacto del servicio, lo que incluye y lo que no, el plazo estimado y la tarifa fija. Si algo no te convence, lo ajustamos.",
        "points": [("Tú haces", "revisas la propuesta y la aceptas en línea."),
                   ("Nosotros", "asignamos un abogado responsable de tu caso."),
                   ("Sin compromiso", "la consulta y la cotización no tienen costo.")],
    },
    {
        "icon": "check-circle",
        "title": "Recibe tu solución",
        "text": "Tu abogado trabaja en el caso y te mantiene al tanto. Revisamos los documentos contigo antes de entregarlos y hacemos los trámites ante las entidades que correspondan.",
        "points": [("Tú haces", "aportas la información y firmas cuando sea necesario."),
                   ("Nosotros", "redactamos, revisamos, radicamos y hacemos seguimiento."),
                   ("Resultado", "documentos listos, revisados y explicados.")],
    },
]

PROCESS_FAQS = [
    ("¿La consulta inicial tiene costo?",
     ["No. La primera conversación para entender tu caso y la cotización son gratuitas y sin compromiso. Solo empiezas a pagar cuando aceptas la propuesta."]),
    ("¿Por qué no publican precios en la página?",
     ["Porque cada caso tiene particularidades —número de socios, clases de una marca, complejidad de un contrato— que cambian el trabajo necesario. Preferimos darte una tarifa fija exacta para tu caso en menos de 24 horas, en lugar de un precio «desde» que luego sube."]),
    ("¿Cómo se paga?",
     ["La forma de pago queda escrita en tu propuesta. Normalmente se paga un anticipo al iniciar y el saldo a la entrega, por transferencia o medios electrónicos. En los planes de asesoría, el pago es mensual."]),
    ("¿Qué pasa si mi caso necesita más trabajo del cotizado?",
     ["La tarifa fija cubre el alcance acordado. Si en el camino surge algo que no estaba previsto, te lo explicamos y te enviamos una cotización adicional antes de hacer cualquier trabajo extra. Nunca recibirás una cuenta que no hayas aprobado."]),
    ("¿Atienden fuera de Antioquia?",
     ["Sí. Trabajamos de forma digital con clientes de toda Colombia. Para reuniones presenciales te recibimos en Rionegro, Antioquia."]),
    ("¿Mi información es confidencial?",
     ["Sí. Toda la información que compartes está protegida por el secreto profesional del abogado y la tratamos conforme a la Ley 1581 de 2012 de protección de datos personales."]),
]

VALUES = [
    ("scale", "Rigor jurídico", "Cada documento se revisa con detalle. La claridad nunca sacrifica la precisión."),
    ("eye", "Transparencia", "Tarifas, plazos y alcances por escrito antes de empezar. Sin letra pequeña."),
    ("zap", "Eficiencia", "Procesos estandarizados donde se puede y atención a la medida donde se necesita."),
    ("users", "Accesibilidad", "Lenguaje claro, respuesta rápida y abogados que puedes contactar de verdad."),
    ("laptop", "Tecnología", "Firma electrónica, radicación digital y seguimiento en línea de tu caso."),
]
